/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class viewfromdatabase extends javax.swing.JFrame {
private String typeview;
    /**
     * Creates new form viewfromdatabase
     * @param typeview
     */
    public viewfromdatabase(String typeview) {
             this.typeview=typeview;  
        initComponents();
         try {
        tablemain();
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(viewfromdatabase.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    private viewfromdatabase() {
            initComponents();
  //To change body of generated methods, choose Tools | Templates.
    }
     public void tablemain() throws ClassNotFoundException, SQLException{
         Connection con=DBconnect.connect();
         Statement statement = con.createStatement();
        if("slots1".equals(typeview)||"slots2".equals(typeview)){
            jLabel1.setText("Data from Slots table");
    jTable1.getColumnModel().getColumn(0).setHeaderValue("Slot ID");
    jTable1.getColumnModel().getColumn(1).setHeaderValue("Plate Number");
    jTable1.getColumnModel().getColumn(2).setHeaderValue("Slot Status");
    jTable1.getColumnModel().getColumn(3).setHeaderValue("Creation Date");
    jTable1.getTableHeader().resizeAndRepaint();
    if(typeview.equals("slots1")){
        java.sql.ResultSet results = statement.executeQuery("SELECT * FROM slots");
while (results.next()) {
    String stat = results.getString(3);
    if(stat.equals("full"))
    {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.addRow(new Object[]{results.getInt(1),results.getString(2),results.getString(3),results.getString(4)}); 
    }
    }    
    }
    else  if(typeview.equals("slots2")){
          java.sql.ResultSet results = statement.executeQuery("SELECT * FROM slots");
while (results.next()) {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.addRow(new Object[]{results.getInt(1),results.getString(2),results.getString(3),results.getString(4)}); 
        
  
}

     }}
        else if("shifts".equals(typeview)){
            jLabel1.setText("Data from Shifts table");    
    jTable1.getColumnModel().getColumn(0).setHeaderValue("Slot ID");
    jTable1.getColumnModel().getColumn(1).setHeaderValue("Book Hours");
    jTable1.getColumnModel().getColumn(2).setHeaderValue("Book Mins");
    jTable1.getColumnModel().getColumn(3).setHeaderValue("Car Payment");
    jTable1.getTableHeader().resizeAndRepaint();
        
java.sql.ResultSet results = statement.executeQuery("SELECT * FROM shifts");
while (results.next()) {
    String stat = results.getString(3);
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.addRow(new Object[]{results.getInt(1),results.getInt(2),results.getInt(3),results.getInt(4)}); 
    
    }
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("jLabel1");

        jButton1.setText("Back to  Admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 this.dispose();
               Adminframe adlogin=new Adminframe();
               adlogin.setVisible(true);
               adlogin.toFront();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewfromdatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewfromdatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewfromdatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewfromdatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewfromdatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
